### ISSUE TITLE
Words

### ISSUE THREAD

**Issue by JavaCakess** [Rodrun/Rek-Warfare#11]
Why does the server object belong to the Window class? Shouldn't it belong to a "Client" or "Game" class? A window is a window for displaying things, leave the networking to the other classes.

:-1: :walking: :boy:

**Comment by Rodrun** [comment]
Lal, old code.
I haven't pushed anything in a bit, my fault, what I currently have is a separate `server` directory that will be handling a Server object and other shit server-related.
Ignore until future commits.
